
# NETWORK #
networks:

  inception:
    name: ${USER}${DOMAIN_SUFFIX}
    driver: bridge

# SERVICES #
services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql/.
    env_file:
      - .env
    environment:
      - ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - USER_PASSWORD_FILE=/run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
    networks:
      - inception
    expose:
      - "3306"
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_root_password
      - ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - USER_PASSWORD_FILE=/run/secrets/wp_user_password
    secrets:
      - db_root_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

# SECRETS #
secrets:

  db_root_password:
    file: ../secrets/.db_root_password
  db_user_password:
    file: ../secrets/.db_user_password
  wp_admin_password:
    file: ../secrets/.wp_admin_password
  wp_user_password:
    file: ../secrets/.wp_user_password

# VOLUMES #
volumes:

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/${USER}${DOMAIN_SUFFIX}/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/data/${USER}${DOMAIN_SUFFIX}/wordpress
      o: bind
      type: none
