
# NETWORK #
networks:

  inception:
    name: ${USER}${DOMAIN_SUFFIX}
    driver: bridge

# SERVICES #
services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql/.
    env_file:
      - .env
    environment:
      - ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - USER_PASSWORD_FILE=/run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
    networks:
      - inception
    expose:
      - "3306"
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_root_password
      - ADMIN_PASSWORD_FILE=/run/secrets/wp_admin_password
      - USER_PASSWORD_FILE=/run/secrets/wp_user_password
    secrets:
      - db_root_password
      - wp_admin_password
      - wp_user_password
    networks:
      - inception
    expose:
      - "9000"
    depends_on:
      - mariadb
      - redis
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    volumes:
      - redis:/data
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "6379"
    restart: always
    logging:
      driver: "none"

#  ftp:
#    container_name: ftp
#    build: ./requirements/bonus/ftp/.
#    volumes:
#      - wordpress:/home/${USER}/wordpress
#    env_file:
#      - .env
#    environment:
#      - FTP_PASSWORD=/run/secrets/ftp_password
#    secrets:
#      - ftp_password
#    networks:
#      - inception
#    ports:
#      - "21:21"
#      - "21100-21110:21100-21110"
#    restart: always


# SECRETS #
secrets:

  db_root_password:
    file: /home/${USER}/data/secrets/.db_root_password
  db_user_password:
    file: /home/${USER}/data/secrets/.db_user_password
  wp_admin_password:
    file: /home/${USER}/data/secrets/.wp_admin_password
  wp_user_password:
    file: /home/${USER}/data/secrets/.wp_user_password
  ftp_password:
    file: /home/${USER}/data/secrets/.ftp_password

# VOLUMES #
volumes:

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/${USER}${DOMAIN_SUFFIX}/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/data/${USER}${DOMAIN_SUFFIX}/wordpress
      o: bind
      type: none

  redis:
    name: redis
    driver: local
    driver_opts:
      device: /home/${USER}/data/${USER}${DOMAIN_SUFFIX}/redis
      o: bind
      type: none
