version: '3'

# NETWORK #
networks:

  inception:
    name: ${USER}${DOMAIN_SUFFIX}
    driver: bridge

# VOLUMES #
volumes:

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/${USER}/data/${USER}${DOMAIN_SUFFIX}/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/${USER}/data/${USER}${DOMAIN_SUFFIX}/wordpress
      o: bind
      type: none

# SERVICES #
services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes:
      - mariadb:/var/lib/mysql/.
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password.txt:ro
      - ../secrets/db_user_password.txt:/run/secrets/db_user_password.txt:ro
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "3306"
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    volumes:
      - wordpress:/var/www/html
      - ../secrets/db_root_password.txt:/run/secrets/db_root_password.txt:ro
      - ../secrets/wp_admin_password.txt:/run/secrets/wp_admin_password.txt:ro
      - ../secrets/wp_user_password.txt:/run/secrets/wp_user_password.txt:ro
    env_file:
      - .env
    networks:
      - inception
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
